name: Build Cross-Platform Binaries

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build cross-platform binaries
      run: |
        npx pkg mcp-simple.js --targets node18-linux-x64,node18-win-x64,node18-macos-x64,node18-macos-arm64
        
    - name: Rename binaries
      run: |
        mv mcp-simple like-i-said-mcp-linux
        mv mcp-simple.exe like-i-said-mcp-win-x64.exe
        mv mcp-simple-macos-x64 like-i-said-mcp-macos-x64
        mv mcp-simple-macos-arm64 like-i-said-mcp-macos-arm64
        
    - name: Create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          like-i-said-mcp-linux
          like-i-said-mcp-win-x64.exe
          like-i-said-mcp-macos-x64
          like-i-said-mcp-macos-arm64
          install-script.sh
        body: |
          ## Zero-Dependency Installation
          
          Install Like-I-Said MCP Server v2 with a single command:
          
          ```bash
          curl -sSL https://raw.githubusercontent.com/endlessblink/like-i-said-mcp-server-v2/main/install-script.sh | bash
          ```
          
          Or download the appropriate binary for your platform:
          
          - **Linux x64**: `like-i-said-mcp-linux`
          - **Windows x64**: `like-i-said-mcp-win-x64.exe`
          - **macOS x64**: `like-i-said-mcp-macos-x64`
          - **macOS ARM64**: `like-i-said-mcp-macos-arm64`
          
          ### Features
          - ✅ Zero Node.js dependency
          - ✅ Single binary installation
          - ✅ Auto-configures Claude Desktop, Cursor, and Claude Code
          - ✅ Cross-platform support (Windows, macOS, Linux)
          - ✅ Lightweight (~45MB) standalone executables
          
          ### Manual Installation
          
          1. Download the binary for your platform
          2. Make it executable: `chmod +x like-i-said-mcp-*`
          3. Configure your MCP client to use the binary path
          
          ### Testing Installation
          
          ```bash
          echo '{"jsonrpc": "2.0", "id": 1, "method": "tools/list"}' | ./like-i-said-mcp-linux
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}